// <auto-generated />
namespace code_first.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Begincreatebasetabel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Begincreatebasetabel));
        
        string IMigrationMetadata.Id
        {
            get { return "201901212031154_Begin create base tabel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
